

import { NavbarDemo } from "@/components/Navbar/Navbar";
import "./globals.css";
import GradientBackground from "@/components/Navbar/Gradient";

export const metadata = {
  title: "Karan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <GradientBackground>
      <NavbarDemo></NavbarDemo>
      <div className="pt-24 ">
      
      
        {children}
        </div>
        </GradientBackground>
      </body>
    </html>
  );
}


