

import { NavbarDemo } from "@/components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Karan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <>
      <NavbarDemo></NavbarDemo>
      <div className="pt-24">
        {children}
        </div>
        </>
      </body>
    </html>
  );
}


