

import { NavbarDemo } from "@/components/Navbar/Navbar";
import Head from "next/head";
import "./globals.css";

import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";

export const metadata = {
  title: "Karan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <>
    <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Acorn:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
    <body >
     
     <BackgroundGradientAnimation>
     <NavbarDemo></NavbarDemo>
     <div className="pt-24 ">
     
     
       {children}
       </div>
       </BackgroundGradientAnimation>
   
     </body>
    </>
    </html>
  );
}


